version: '3.8'
services:
  # Database for Kong
  kong-database:
    image: postgres:15
    container_name: kong-database
    restart: always
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    ports:
      - 5432:5432
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - kong-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Run initial database migrations for Kong
  kong-migrations:
    image: kong/kong-gateway:latest
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - kong-network
    
  # Kong API Gateway
  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    restart: always
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 8000:8000  # Proxy port
      - 8443:8443  # Proxy port (SSL)
      - 8001:8001  # Admin API
      - 8444:8444  # Admin API (SSL)
      - 8002:8002  # Admin GUI
    depends_on:
      - kong-migrations
    networks:
      - kong-network
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 5
  
  # Konga - Kong Admin UI
  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=kong
    ports:
      - 1337:1337
    depends_on:
      - kong
    networks:
      - kong-network

volumes:
  kong_data:

networks:
  kong-network:
    driver: bridge