global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics

  # Serviciile cu FastAPI trebuie să aibă activate endpoint-uri Prometheus
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    metrics_path: /metrics

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8000']
    metrics_path: /metrics

  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:8000']
    metrics_path: /metrics

  - job_name: 'database-service'
    static_configs:
      - targets: ['database-service:8001']
    metrics_path: /metrics