apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: microservices
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:
      - name: auth-service
        url: http://auth-service:8000
        routes:
          - name: auth-service-route
            paths:
              - /auth
            strip_path: true

      - name: product-service
        url: http://product-service:8000
        routes:
          - name: product-service-route
            paths:
              - /products
            strip_path: true

      - name: orders-service
        url: http://orders-service:8000
        routes:
          - name: orders-service-route
            paths:
              - /orders
            strip_path: true

      - name: payment-service
        url: http://payment-service:8000
        routes:
          - name: payment-service-route
            paths:
              - /payment
            strip_path: true
      
      - name: database-service
        url: http://database-service:8000
        routes:
          - name: database-service-route
            paths:
              - /database
            strip_path: true 