apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservices 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ghcr.io/ioio21/auth-service:latest
        envFrom:
        - secretRef:
            name: auth-secret
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
spec:
  selector:
    app: auth-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: ghcr.io/ioio21/product-service:latest
        envFrom:
        - secretRef:
            name: product-secret
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
spec:
  selector:
    app: product-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: ghcr.io/ioio21/orders-service:latest
        envFrom:
        - secretRef:
            name: orders-secret
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: microservices
spec:
  selector:
    app: orders-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: ghcr.io/ioio21/payment-service:latest
        envFrom:
        - secretRef:
            name: payment-secret
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microservices
spec:
  selector:
    app: payment-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP 