name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt
        pip install pylint pytest

    - name: Lint with pylint
      run: |
        echo "Running pylint..."
        pylint ./backend

    # - name: Run tests with pytest
    #   run: |
    #     echo "Running pytest..."
    #     pytest ./backend

  build-containers:
    name: Build Docker Containers
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build Auth Service Container
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Auth.Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
        
        
        
        
